<!-- FOOTER -->
		<div id="footer">
			<div class="left">
				Copyright &copy; 2011. Encore Bridal. All Rights Reserved.<br />
				Finely Crafted by <a href="http://www.proofbranding.com" title="Proof Branding">Proof Branding.</a>
			</div>

			<div class="right">
				<a href="#"><img src="<?php echo $this->getSkinUrl('images/spacer.gif'); ?>" class="social_networking_icons pinterest right" /></a>
				<a href="#"><img src="<?php echo $this->getSkinUrl('images/spacer.gif'); ?>" class="social_networking_icons rss right" /></a>
				<a href="http://www.facebook.com/EncoreBridalFanPage" target="_blank"><img src="<?php echo $this->getSkinUrl('images/spacer.gif'); ?>" class="social_networking_icons facebook right" /></a>
				<a href="http://twitter.com/#!/encorebridal" target="_blank"><img src="<?php echo $this->getSkinUrl('images/spacer.gif'); ?>" class="social_networking_icons twitter right" /></a>
			</div><br clear="both" />
		</div>