<!-- SLIDER -->
		<div id="slider">
			<div class="slider_content hide" rel="<?php echo $this->getSkinUrl('images/feature.jpg'); ?>" id="slider_1">
				&nbsp;
			</div>
			<div class="slider_content hide" rel="<?php echo $this->getSkinUrl('images/feature.jpg'); ?>" id="slider_2">
				&nbsp;
			</div>
			<div id="slider_navigation">
				<a href="#"><img src="<?php echo $this->getSkinUrl('images/spacer.gif'); ?>" class="slider_item" id="button_1" /></a>
				<a href="#"><img src="<?php echo $this->getSkinUrl('images/spacer.gif'); ?>" class="slider_item" id="button_2" /></a>
			</div>
		</div>

		<hr />