<?php
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

?>
<?php $_product = $this->getProduct(); ?>
<?php $buttonTitle = $this->__('Add to Wishlist'); ?>
<?php if($_product->isSaleable()): ?>
<form id="wishlist_form" action="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>">
    <input type="submit" value="<?php echo strtoupper($this->__('Add to Dressing Room')) ?>"/>
</form>
    <!--<div class="add-to-wishlist">
        <a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" class="link-wishlist"><?php echo $this->__('Add to Wishlist') ?></a>
    </div>-->
<?php endif; ?>
