<h3>More Information</h3>
<ul id="consigner-navigation" class="vertical-navigation">
  <li class="how-to-consign"><a href="/consignors/how-to-consign">how to consign</a></li>
  <li class="consignment-terms"><a href="/consignors/consignment-terms">consignment terms & conditions</a></li>
  <li class="reviews"><a href="/reviews">reviews</a></li>
</ul>

<div class="consigner-testimonial">
  "After months without any success, I was fortunate to discover Encore Bridal's ad and contacted the owner, Julie. Her professional and prompt responses to my many questions put my fears to rest about sending such a valuable dress to someone I had never met. Encore's excellent marketing of my daughter's dress resulted in it being sold within two months. <strong>I would highly recommend Julie and Encore Bridal to anyone</strong> hoping to sell, or get a great deal on, a new or nearly new wedding gown." —Review by Lynn L. on Wedding Wire 
</div>
