<ul id="consigner-navigation" class="vertical-navigation">
  <li class="how-to-consign"><a href="/consignors/how-to-consign">how to consign</a></li>
  <li class="consignment-terms"><a href="/consignors/terms">consignment terms & conditions</a></li>
  <li class="reviews"><a href="/reviews">reviews</a></li>
</ul>


<div class="consigner-testimonial">
    <?php $collection = Mage::getModel("testimonial/testimonial")->getCollection(); ?>
    <?php $collection->setOrder('testimonial_position', 'ASC'); ?>
    <?php $testimonials = $collection->load(); ?>
    <?php $i = 0;?>
    <?php if ($testimonials->count() > 0): ?>
    <?php foreach ($testimonials as $testimonial): ?>
        <?php if ($i == 1) break; ?>
        <div class="review">
            <h5><?php echo $testimonial->getTestimonialName(); ?></h5>
            <?php echo $testimonial->getTestimonialText(); ?>
        </div>
        <?php $i++; ?>
    <?php endforeach; ?>

    <?php endif;?>
</div>
