<div class="consigner-testimonial contact-faq-sidebar">
    <h3>Top 5 Questions</h3>
    <a href="/customers/faqs/#9">How can I see your dresses in person?</a>
    <a href="/customers/faqs/#15">My gown doesn’t meet the selling qualifications. Will you make an exception?</a>
    <a href="/customers/faqs/#16">How does your consignment process work?</a>
    <a href="/customers/faqs/#12">Who do you recommend for alterations?</a>
    <a href="/customers/faqs/#14">When will my return be processed?</a>
</div>
