<?php
/*
<h3>More Information</h3>
<ul id="customers-navigation" class="vertical-navigation">
  <li class="privacy-policy"><a href="/customers/privacy_policy">Privacy Policy</a></li>
  <li class="faq"><a href="/customers/faqs">FAQs</a></li>
  <li class="terms-of-service"><a href="/customers/terms-of-use">Terms of Service &amp; Use</a></li>
  <li class="customer-service"><a href="/customers/customer-service">Customer Service</a></li>
  <li class="reviews"><a href="/reviews">Reviews</a></li>
  <li class="designer-bios"><a href="/customers/designer-bios">Designer Bios</a></li>
</ul>

<div class="consigner-testimonial">
  "After months without any success, I was fortunate to discover Encore Bridal's ad and contacted the owner, Julie. Her professional and prompt responses to my many questions put my fears to rest about sending such a valuable dress to someone I had never met. Encore's excellent marketing of my daughter's dress resulted in it being sold within two months. <strong>I would highly recommend Julie and Encore Bridal to anyone</strong> hoping to sell, or get a great deal on, a new or nearly new wedding gown." —Review by Lynn L. on Wedding Wire 
</div>
*/ ?>
