<ul id="for-brides-navigation" class="vertical-navigation">
  <li class="privacy-policy"><a href="#">Privacy Policy</a></li>
  <li class="reviews"><a href="/reviews">Reviews</a></li>
  <li class="terms-of-service"><a href="/terms-of-service">Terms of Service &amp; Use</a></li>
  <li class="customer-service"><a href="/customer-service">Customer Service</a></li>
  <li class="survey"><a href="/survey">Survey</a></li>
  <li class="designer-bios"><a href="/designer-bios">Designer Bios</a></li>
</ul>
