<h3>More Information</h3>
<ul id="for-brides-navigation" class="vertical-navigation">
  <li><a href="/for_brides/shipping_info/">Shipping info</a></li>
  <li><a href="/for_brides/return_policy/">Return Policy</a></li>
  <li><a href="/for_brides/alterations/">Alterations</a></li>
  <li><a href="/for_brides/layaway/">Layaway</a></li>
  <li><a href="/for_brides/condition_guidelines/">Condition Guidelines</a></li>
  <li><a href="/for_brides/preferred_vendors/">Preferred Vendors</a></li>
  <li class="reviews"><a href="/reviews">Reviews</a></li>
  <li><a href="/webforms/index/index/id/4/">Virtual Stylist</a></li>				
</ul>

<div class="consigner-testimonial">
  "After months without any success, I was fortunate to discover Encore Bridal's ad and contacted the owner, Julie. Her professional and prompt responses to my many questions put my fears to rest about sending such a valuable dress to someone I had never met. Encore's excellent marketing of my daughter's dress resulted in it being sold within two months. <strong>I would highly recommend Julie and Encore Bridal to anyone</strong> hoping to sell, or get a great deal on, a new or nearly new wedding gown." —Review by Lynn L. on Wedding Wire 
</div>
