<h3>More Information</h3>
<ul id="about-navigation" class="vertical-navigation">
  <li class="who-we-are"><a href="/about/">who we are</a></li>
  <li class="showroom"><a href="/about/showroom">showroom</a></li>
  <li class="events"><a href="/about/events">events</a></li>
  <li class="press"><a href="/about/press">press</a></li>
  <li class="beyond-bridal"><a href="/about/beyond-bridal">beyond bridal</a></li>
</ul>
