<img src="<?php echo $this->getSkinUrl() ?>/images/free-shipping.png" alt="Free Shipping" />

<h3>More Information</h3>
<ul id="about-navigation" class="vertical-navigation">
  <li class="who-we-are"><a href="/about/">who we are</a></li>
  <li class="showroom"><a href="/about/showroom">showroom</a></li>
  <li class="events"><a href="/about/events">events</a></li>
  <li class="press"><a href="/about/press">press</a></li>
  <li class="beyond-bridal"><a href="/about/beyond-bridal">beyond bridal</a></li>
</ul>

<div class="consigner-testimonial">
  "After months without any success, I was fortunate to discover Encore Bridal's ad and contacted the owner, Julie. Her professional and prompt responses to my many questions put my fears to rest about sending such a valuable dress to someone I had never met. Encore's excellent marketing of my daughter's dress resulted in it being sold within two months. <strong>I would highly recommend Julie and Encore Bridal to anyone</strong> hoping to sell, or get a great deal on, a new or nearly new wedding gown." —Review by Lynn L. on Wedding Wire 
</div>
