<?php
/* 
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

?>
<hr />
<?php
preg_match("/index\.php\/(\w*)[\.\/]?/", $_SERVER['REQUEST_URI'], $matches);
if(!isset($matches[1]))
{
    $str = preg_replace("/index\.php/", "", $_SERVER['SCRIPT_NAME']);
    preg_match("/(\w*)[\.\/]?/", str_replace($str, "", $_SERVER['REQUEST_URI']), $matches);
    $matches[1];
}
?>
<?php if($matches[1] == "dresses") { ?>
<!-- SEARCH BAR -->
<?php
$attributesInfo = Mage::getResourceModel('eav/entity_attribute_collection')->addFieldToFilter('attribute_code', 'designer_select');
$attribute = $attributesInfo->getFirstItem();
$designer_select = $attribute->getSource()->getAllOptions();

$attributesInfo = Mage::getResourceModel('eav/entity_attribute_collection')->addFieldToFilter('attribute_code', 'neckline');
$attribute = $attributesInfo->getFirstItem();
$necklines = $attribute->getSource()->getAllOptions();

$attributesInfo = Mage::getResourceModel('eav/entity_attribute_collection')->addFieldToFilter('attribute_code', 'silhouette');
$attribute = $attributesInfo->getFirstItem();
$silhouettes = $attribute->getSource()->getAllOptions();

$attributesInfo = Mage::getResourceModel('eav/entity_attribute_collection')->addFieldToFilter('attribute_code', 'fabric');
$attribute = $attributesInfo->getFirstItem();
$fabrics = $attribute->getSource()->getAllOptions();

$attributesInfo = Mage::getResourceModel('eav/entity_attribute_collection')->addFieldToFilter('attribute_code', 'bridal_style');
$attribute = $attributesInfo->getFirstItem();
$bridal_styles = $attribute->getSource()->getAllOptions();

$attributesInfo = Mage::getResourceModel('eav/entity_attribute_collection')->addFieldToFilter('attribute_code', 'body_type');
$attribute = $attributesInfo->getFirstItem();
$body_types = $attribute->getSource()->getAllOptions();

?>
		<div class="span-6">
			<!-- MY DRESSING ROOM -->
			<div class="small_box_2">
				<a href="<?php echo $this->helper('wishlist/data')->getListUrl();?>" class="more">Go To</a>
				<h3><a href="<?php echo $this->helper('wishlist/data')->getListUrl();?>">My Dressing Room</a></h3>
			</div>

			<!-- QUICK SEARCH -->
			<div id="quick_search_wrapper">
			<div id="quick_search">
			<div id="quick_search_son">
                            <form method="get"  action="<?php echo $this->helper('catalogsearch')->getResultUrl() ?>" id="quick_search_form">
				<h4>Quick Search</h4>
                                <hr />
                                <a href="#" class="more">NEW ARRIVALS</a><br/>
                                <a href="#" class="more">RECENTLY SOLD</a><br/>
                                <a href="#" class="more">LAST CHANCE</a><br/>
				<hr />
				<label>Size:</label> <span id="search_size_slider_value"></span><br />
				<div id="search_size_slider"></div>
				<hr />
				<label>Height:</label> <span id="search_height_slider_value"><span id="search_height_min_inches">5'2</span> - <span id="search_height_max_inches">5'3</span></span>
				<div id="search_height_slider"></div>
				<hr />
				<label>Designer</label><br />
				<select name="designer">
                                    <option value="0">All designers</option>
					<?php
                                        foreach($designer_select as $value)
                                        {
                                            if($value['value'] != "" && $value['label'] != "")
                                            echo "<option value='".$value['value']."'>".$value['label']."</option>";
                                        }
                                        ?>
				</select>
				<hr />
				<label>Price:</label> <span id="search_cost_slider_value"></span>
				<div id="search_cost_slider"></div>
				<hr />
				<a href="#" class="more" id="refine_search">Refine Search</a>

                                <div class="hide" id="refine_search_options">
                                    <hr>
                                    <p><label>Neckline:</label><br>
                                    <select name="neckline">
                                    <option value="0">All necklines</option>
					<?php
                                        foreach($necklines as $value)
                                        {
                                            if($value['value'] != "" && $value['label'] != "")
                                            echo "<option value='".$value['value']."'>".$value['label']."</option>";
                                        }
                                        ?>
                                    </select></p>
                                    <hr>

                                    <p><label>Silhouette:</label><br>
                                    <select name="silhouette">
                                    <option value="0">All silhouettes</option>
					<?php
                                        foreach($silhouettes as $value)
                                        {
                                            if($value['value'] != "" && $value['label'] != "")
                                            echo "<option value='".$value['value']."'>".$value['label']."</option>";
                                        }
                                        ?>
                                    </select></p>
                                    <hr>

                                    <p><label>Fabric:</label><br>
                                    <select name="fabric">
                                            <option value="0">All fabrics</option>
					<?php
                                        foreach($fabrics as $value)
                                        {
                                            if($value['value'] != "" && $value['label'] != "")
                                            echo "<option value='".$value['value']."'>".$value['label']."</option>";
                                        }
                                        ?>
                                    </select></p>
                                    <hr>

                                    <p><label>Bridal Style:</label><br>
                                    <select name="bridal_style">
                                            <option value="0">All Bridal Styles</option>
					<?php
                                        foreach($bridal_styles as $value)
                                        {
                                            if($value['value'] != "" && $value['label'] != "")
                                            echo "<option value='".$value['value']."'>".$value['label']."</option>";
                                        }
                                        ?>
                                    </select></p>
                                    <hr>

                                    <p><label>Body Type:</label><br>
                                    <select name="body_type">
                                            <option value="0">All Body Types</option>
					<?php
                                        foreach($body_types as $value)
                                        {
                                            if($value['value'] != "" && $value['label'] != "")
                                            echo "<option value='".$value['value']."'>".$value['label']."</option>";
                                        }
                                        ?>
                                    </select></p>
				</div>


				<hr />
				<input type="submit" value="SEARCH" name="search" id="submit_quick_search" onclick=""/>
                                </form>
			</div><!-- CLOSE QUIICK SEARCH SON -->
			</div><!-- CLOSE QUICK SEARCH -->
			</div><!-- CLOSE QUICK SEARCH WRAPPER -->
		</div>
<?php } ?>

<script type="text/javascript">
    $j(document).ready(function() {
			$j('#refine_search').toggle(function(e) {
				//e.preventDefault();
				$j('#refine_search_options').slideDown();
			}, function() {
				//e.preventDefault();
				$j('#refine_search_options').slideUp();
			});
		});
</script>