<!-- BOXES -->
		<div class="span-12">
			<!-- ABOUT ENCORE -->
			<div id="about_encore">
				<h2 class="paint"><?php echo $this->__("boxes_learn_more");?></h2>
				<a href="/about" class="more"><?php echo $this->__("boxes_about_us");?></a>
				<img src="<?php echo $this->getSkinUrl('images/video_about.jpg'); ?>" />
			</div>
		</div>

		<div class="span-12 last">
			<!-- CONSIGNOR BOX -->
			<div id="consignor">
				<h2><?php echo $this->__("boxes_consignor_header");?></h2>
				<h3><?php echo $this->__("boxes_consignor_text");?></h3>
				<a href="<?php echo $this->getUrl('')."consignors"?>" class="more"><?php echo $this->__("boxes_consignor_coral_serif");?></a>
			</div>

			<div class="span-6">
				<!-- RECENT BLOG POST -->
				<div class="small_box_2">
					<h5><?php echo $this->__("boxes_recent_blog_gray_serif");?></h5>
					<h3><a href="/blog" class="arrow"><?php echo $this->__("boxes_recent_blog_coral_serif");?></a></h3>
				</div>
			</div>

			<div class="span-6 last">
				<!-- STYLIST -->
				<div class="small_box">
					<h5><?php echo $this->__("boxes_stylist_gray_serify");?></h5>
					<h3><a href="/about/events" class="arrow"><?php echo $this->__("boxes_stylist_coral_serify");?></a></h3>
				</div>
			</div>
		</div>
		<br clear="both" />

		<hr />
