<!-- FEATURED ON -->
		<hr />
		<h2 class="paint">featured on</h2>

		<div id="featured_on">
                    <a href="http://www.nytimes.com/" class="logo" target="_blank"><img src="<?php echo $this->getSkinUrl('images/logo_the_new_york_times.gif'); ?>" alt="The New York Times" /></a>
			<a href="http://www.smartmoney.com/" class="logo" target="_blank"><img src="<?php echo $this->getSkinUrl('images/logo_smart_money.gif'); ?>" alt="Smart Money" /></a>
			<a href="http://www.chicagotribune.com/" class="logo" target="_blank"><img src="<?php echo $this->getSkinUrl('images/logo_chicago_tribune.gif'); ?>" alt="Chicago Tribune" /></a>
			<a href=" http://www.getmarried.com/" class="logo" target="_blank"><img src="<?php echo $this->getSkinUrl('images/logo_get_married.gif'); ?>" alt="Get Married" /></a>
			<a href="http://www.thebrideandbloom.com/" class="logo" target="_blank"><img src="<?php echo $this->getSkinUrl('images/logo_bride_and_bloom.gif'); ?>" alt="Bride and Bloom" /></a>
		</div>

		<hr />