<!-- FEATURED ON -->
		<hr />
		<h2 class="paint">featured on</h2>

		<div id="featured_on">
            <a href="http://www.nytimes.com/2009/02/01/fashion/weddings/01fieldnotes.html?_r=3&scp=1&sq=bethany%20kandel%20secondhand&st=cse" class="logo" target="_blank"><img src="<?php echo $this->getSkinUrl('images/logo_the_new_york_times.gif'); ?>" alt="The New York Times" /></a>
			<a href="http://www.smartmoney.com/spending/deals/with-this-used-dress-i-thee-wed-19381/" class="logo" target="_blank"><img src="<?php echo $this->getSkinUrl('images/logo_smart_money.gif'); ?>" alt="Smart Money" /></a>
			<a href="http://www.chicagotribune.com/business/sc-cons-0902-started-20100902,0,3514687.story" class="logo" target="_blank"><img src="<?php echo $this->getSkinUrl('images/logo_chicago_tribune.gif'); ?>" alt="Chicago Tribune" /></a>
			<a href="http://www.getmarried.com/magazine/view/" class="logo" target="_blank"><img src="<?php echo $this->getSkinUrl('images/logo_get_married.gif'); ?>" alt="Get Married" /></a>
			<a href="http://www.thebrideandbloom.com/" class="logo" target="_blank"><img src="<?php echo $this->getSkinUrl('images/logo_bride_and_bloom.gif'); ?>" alt="Bride and Bloom" /></a>
		</div>

		<hr />
