<!-- HEADER -->
		<div id="header">
			<!-- TOP NAVIGATION -->
			<div class="right" id="top_nav">
				<div id="search">
          <form method="get" action="<?php echo $this->helper('catalogsearch')->getResultUrl() ?>" id="search_mini_form">
              <input type="text" class="text" value="" name="q" /><input type="submit" class="submit" value="SEARCH" name="submit" />
              <div class="search-autocomplete" id="search_autocomplete" style="display: none;"></div>
              <script type="text/javascript">
                //&lt;![CDATA[
                  var searchForm = new Varien.searchForm('search_mini_form', 'search', 'Search entire store here...');
                  searchForm.initAutocomplete('<?php echo $this->getUrl('') ?>catalogsearch/ajax/suggest/', 'search_autocomplete');
                //]]&gt;
              </script>
          </form>
        </div>
        <?php // echo $this->getChildHtml('topLinks') ?>
        <div class="right" style="clear:right;">
          <?php if($this->helper('customer')->isLoggedIn()): ?>
            <a href="/index.php/customer/account/" title="My Account" class="login">MY ACCOUNT</a> |
          <?php else: ?>
            <a href="/index.php/customer/account/login/" title="LOGIN" class="login">LOGIN</a> |
          <?php endif; ?>
          <a href="/index.php/checkout/cart/" title="CART">CART</a> |
          <a href="/index.php/contacts">CONTACT</a> |
          <a href="#">310.545.1409</a>
        </div>
			</div>
			<!-- LOGO -->
			<div id="logo"><a href="<?php echo $this->getUrl('') ?>"><img src="<?php echo $this->getSkinUrl('images/logo.png'); ?>" alt="Encore Bridal" /></a></div>
			<!-- NAVIGATION -->
			<div id="navigation">
				<ul>
					<li class="home"><a href="<?php echo $this->getUrl('') ?>">home</a></li>
					<li class="dresses"><a href="<?php echo $this->getUrl('')."dresses.html"?>">Dresses</a></li>
					<li class="accessories"><a href="<?php echo $this->getUrl('')."accessories"?>">Accessories</a></li>
					<li class="for_brides"><a href="<?php echo $this->getUrl('')."for-brides"?>">for brides</a></li>
					<li class="consignors"><a href="<?php echo $this->getUrl('')."consignors"?>">consignors</a></li>
					<li class="about"><a href="<?php echo $this->getUrl('')."about"?>">about</a></li>
					<li class="blog"><a href="/blog">blog</a></li>
				</ul>
			</div>
		</div><br clear="both" />

                <?php
                //require_once 'app/Mage.php';
                Mage::app();

                function get_categories()
                {

                    $category = Mage::getModel('catalog/category');
                    $tree = $category->getTreeModel();
                    $tree->load();

                    $ids = $tree->getCollection()->getAllIds();

                    if ($ids)
                    {
                        foreach ($ids as $id)
                        {
                            $cat = Mage::getModel('catalog/category');
                            $cat->load($id);
                            if($cat->getName() != "Root Catalog" && $cat->getName() != "Default Category")
                            {
                              if($cat->getName() == 'dresses' || $cat->getName() == 'accessories'){
                                echo "<li class='".strtolower($cat->getName())."'><a href='".$cat->getUrl()."'>".strtoupper($cat->getName())."</a></li>";
                              }
                            }
                        }
                    }

                }
                ?>
