<?php
/* 
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

?>
<?php
$pages = Mage::getModel('cms/page')->getCollection()->load();

preg_match("/index\.php\/(\w*)[\.\/]?/", $_SERVER['REQUEST_URI'], $matches);
if(!isset($matches[1]))
{
    $str = preg_replace("/index\.php/", "", $_SERVER['SCRIPT_NAME']);
    preg_match("/(\w*)[\.\/]?/", str_replace($str, "", $_SERVER['REQUEST_URI']), $matches);
}
$links_array = array();

foreach($pages as $page)
{
    $data = $page->getData();
    if(preg_match("/".$matches[1]."\//", $data['identifier']))
        $links_array[] = $data;
}

?>

<ul>
    <?php
    foreach($links_array as $value)
    {
        if(strpos($_SERVER['SCRIPT_URI'], $this->getUrl($value['identifier'])) !== false)
            echo "<li><a href='".$this->getUrl($value['identifier'])."' class='current_link'>".$value['title']."</a></li>";
        else
            echo "<li><a href='".$this->getUrl($value['identifier'])."'>".$value['title']."</a></li>";
    }
    ?>
</ul>