                        <?php
                            Mage::register('current_gallery', Mage::getModel('gallery/gallery'));
                            $gal = Mage::registry('current_gallery');
                            $items = $gal->getGallery();

                            $slider_images = "";
                            $slider_navigation = "";
                            if(count($items)){
                                $cnt = 1;
                            foreach($items as $item)
                            {
                                $slider_images .= '<div class="slider_content hide" rel="'.$item->getImageUrl().'" id="slider_'.$cnt.'">'.
                                                    '&nbsp;'.
                                                 '</div>';
                                $slider_navigation .= '<a href="#"><img src="'.$this->getSkinUrl('images/spacer.gif').'" class="slider_item" id="button_'.$cnt.'" /></a>';
                                $cnt++;
                            }
                            }
                        ?>

<!-- SLIDER -->
		<div id="slider">
                    <?php echo $slider_images;?>

                    <div id="slider_navigation">
                        <?php echo $slider_navigation;?>
                    </div>
		</div>

		<hr />