<?php $posts = Mage::getModel("blog/api")->getPosts(); ?>
<?php
$pager = Mage::getConfig()->getBlockClassName('blog/blog');
$posts_pager = new $pager();

$start = null;
$end = null;
if ((int) Mage::getStoreConfig('blog/blog/perpage') != 0) {
    preg_match_all("/\/?(\w+)\/?/", $_SERVER['REQUEST_URI'], $matches);
    if($matches[1][count($matches[1]) - 1] == 'blog')
    {
        $start = 0;
        $end = (int) Mage::getStoreConfig('blog/blog/perpage');
    }
    else if($matches[1][count($matches[1]) - 2] == 'page')
    {
        $start = ((int)$matches[1][count($matches[1]) - 1] - 1) * (int) Mage::getStoreConfig('blog/blog/perpage');
        $end = ((int)$matches[1][count($matches[1]) - 1]) * (int) Mage::getStoreConfig('blog/blog/perpage');
    }
}
?>
<?php $posts_api = Mage::getModel('blog/api');?>

<?php $cnt = 0; foreach ($posts as $post): ?>
<?php
if($start != null)
    if($cnt < $start) {$cnt++; continue;}
if($end != null)
    if($cnt >= $end) break;
?>
<div class="postWrapper">
    <div class="postTitle">
        <h2><a href="<?php echo $posts_api->getPostUrl($post->getId()); ?>" ><?php echo $post->getTitle();?></a></h2>
        <h3><?php echo date("m.d.Y", strtotime($post->getCreatedTime())); ?></h3>
    </div>
    <div class="postContent"><?php echo $post->getShortContent(); ?></div>
    
    <?php echo $this->getBookmarkHtml($post) ?>
    <div class="tags"><?php echo $this->getTagsHtml($post) ?></div>
    <!--<div class="postDetails">
        <?php if($this->getCommentsEnabled()): ?>
        <?php echo $post->getCommentCount(); ?> <a href="<?php echo $post->getAddress(); ?>#commentBox" >Comments</a> | 
        <?php endif; ?>
        <?php $postCats = $post->getCats(); ?>
        <?php if(!empty($postCats)):?>
            <?php echo Mage::helper('blog')->__('Posted in');?>
            <?php foreach($postCats as $title=>$url): ?>
                <a href="<?php echo $url; ?>"><?php echo $title; ?></a> 
            <?php endforeach;?> 
        <?php else:?>
             <?php echo Mage::helper('blog')->__('Posted');?>
        <?php endif;?><?php echo$this->__("By");?> <?php echo $post->getUser(); ?></div>-->
</div>
<?php $cnt++; endforeach; ?>
<?php echo $posts_pager->getPages(); ?>
